### PR TITLE
Enhance cmake support

### PR DESCRIPTION
**Pull request by xantares**

### CODE REVIEW

**Comment by liclac** [comment]
Minor nitpick: the rest of `patches/PSP.cmake` uses `func(args)`, not `func (args)`.

Other than that, this looks solid to me, this is stuff I've been annoyed with before.

**Comment by xantares** [comment]
@liclac ok, done

**Comment by xantares** [comment]
@liclac could you merge this ?

**Comment by liclac** [comment]
@xantares No merge access, sorry D:

(If someone wanted to grant it to me, I'd be down for some stewardship for sure.)

**Comment by xantares** [comment]
cc @artart78 @tyranid

**Comment by tyranid** [comment]
I've no way of tested this these days, but it looks reasonable enough.

**Pull request merged**
