### PR TITLE
Replace repo with psp-pacman repository

### PR DESCRIPTION
**Pull request by sharkwouter**
This PR is not done yet, but it will do the following:

- Replace all scripts with PSPBUILD files. This allows for building the libraries with psp-makepkg from psp-pacman.
- Automated builds for the library packages.
- A pacman repository hosted as a release. This is also automatically build.

This will require a change to the psptoolchain repo and the psp-pacman repo. The container used for building the packages is also build automatically and currently hosted on my github account. It should probably be transfered to pspdev before merging.

This takes some code from the vita sdk's packages repo.

### CODE REVIEW

**Comment by sharkwouter** [comment]
This is a draft, because it doesn't quite work yet. Not all packages build and the step for creating the repo database file has not been added yet. A README is also still missing.

**Comment by sajattack** [comment]
This breaks every notion of backwards compatibility. I think you should make a new repo.

**Comment by sharkwouter** [comment]
I do agree, but I cannot create repos

**Comment by sharkwouter** [comment]
Could you perhaps make pspdev/packages? Then I'll make a PR there

**Comment by sajattack** [comment]
You can create a personal repo, and when it's ready, we can fork it or you can transfer it.

**Comment by sharkwouter** [comment]
I'm going to close this in favor of using a new repository.

**Pull request closed without merging**
