### PR TITLE
Use psp-g++ as compiler for squirrel

### PR DESCRIPTION
**Pull request by sharkwouter**
It was failing to build in my docker environment with an error saying I didn't have c++ compiler. Using psp-g++ fixes this.

### CODE REVIEW

**Comment by carstene1ns** [comment]
This is actually a build system bug then. `CC` should never be used for c++ compiler.

**Comment by sharkwouter** [comment]
Good point. I'm not quite sure how that could be solved, though. It's a bit odd that it will use gcc. Maybe I should remove the CC variable there?

**Comment by carstene1ns** [comment]
Have looked at the source. They really compile cpp files with gcc there. :/ So this patch is ok.
There is also version 3.1 released since then, but it would involve further patching.

**Comment by sharkwouter** [comment]
This seems to no longer be an issue with the new GCC version. GCC will compile C++ files just fine. Should we still apply this change?

**Comment by carstene1ns** [comment]
I would say, let's stay like we have it now. Since it works (...and hope they fix their build system one day)

**Comment by sharkwouter** [comment]
Okay, then I'll close it for now.

**Pull request closed without merging**
